print("A fórmula da distância entre dois pontos é a seguinte:D=(x2-x1)^2+(y2-y1)^2."
"Dados dois pontos (x1, y1) e (x2, y2), encontrar a distância entre eles")
x1 =int(input("Digite o valor do ponto x1: "))
x2 =int(input("Digite o valor do ponto x2: "))
y1 =int(input("Digite o valor do ponto y1: "))
y2 =int(input("Digite o valor do ponto y2: "))
dist = (x2-x1)**2+(y2-y1)**4
print("Sua distancia é: ",+dist)